### ISSUE TITLE
Release null safe version

### ISSUE THREAD

**Issue by shilangyu** [comigor/fuzzy#20]
I checked and all of your dependencies except latinize have released a null safe version. I have opened an issue on latinize's end: https://github.com/lucasmafra/latinize/issues/3. Once they release it, could you release a null safe version? Thanks.

Sorry if that was already your plan, then this issue can serve for tracking progress.

**Comment by comigor** [comment]
Sure, thanks for opening the issue!

**Comment by comigor** [comment]
Actually, now we've already released the `0.4.0-nullsafety.0` version, with `latinize ^0.1.0-nullsafety`.
What changes do you feel it still needs?

**Comment by shilangyu** [comment]
Hmm, I guess my request was unnecessary. I just thought `x.x.x-nullsafety.x` releases are seen as pre-releases. I will use that then. Feel free to close this issue, thanks!
